### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by robinpdev** [okikio/twitter-media#2]
I went to the site and none of the samples work. All of them say "invalid url", can you confirm this?

**Comment by okikio** [comment]
It seems there's some sort of bug, thanks for bringing it to my attention I'll take a look

**Comment by okikio** [comment]
@robinpdev I've pushed a fix, please let me know if you still notice the problem

**Comment by nussbaumer-dominik** [comment]
It still seems to be bugged. When using Sample 1 it returns a "SyntaxError: Invalid header name.". After clicking on it a second time it loads a video, but it can't be displayed because "no video with supported format and MIME-Type found".

**Comment by okikio** [comment]
Sorry, this is a Postgres issue, Supabase switched from URLs I thought I had caught all the places where I use Supabase but I missed one.

Thanks for bring this to my attention a fix is currently being drafted

**Comment by okikio** [comment]
@nussbaumer-dominik This should now be fixed, please take a look

**Comment by nussbaumer-dominik** [comment]
It's working in Chrome now but in Firefox the second problem with the MIME Type still persists. However, that could also be related to my extensions or something else maybe.

**Comment by okikio** [comment]
@nussbaumer-dominik It might be a caching issue try running https://inthistweet.app in Firefox Private Mode

**Comment by nussbaumer-dominik** [comment]
None of the samples work in Firefox Private Mode and turning off all extensions also doesn't change that.

**Comment by okikio** [comment]
It seems Firefox CORS and Twitter have some issues in private mode, sorry my bad (I'll look into that). But on Non-private Firefox it seems to work as expected 
![CleanShot 2024-02-10 at 01 33 45@2x](https://github.com/okikio/inthistweet/assets/17222836/d5eea3db-f23b-4a65-86b3-475a3ae7fd30)


What version of Firefox are you using? I'm currently using v122.0.1
